#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <time.h>
#include <ctype.h>
#include <string.h>

/*struct student
{
    char name[10];
    int age;
    char gender;
    int num;

}a[20];

int main()
{
    int studentsN;
    printf("How many students are you going to enter (max:20): ");
    scanf("%d",&studentsN);
    for (int i = 0; i < studentsN; i++)
    {
        printf("Enter the name: ");
        fflush(stdin);
        scanf("%s", &a[i].name);
        printf("How old is the student: ");
        scanf("%d", &a[i].age);
        printf("The student's gender: ");
        fflush(stdin);
        scanf("%c", &a[i].gender);
        printf("The student's number: ");
        scanf("%d", &a[i].num);
    }

    for (int i = 0; i < studentsN; i++)
    {
        printf("%d. student's card:\nName:%s\nAge:%d\nGender:%c\nNum:%d",i+1,a[i].name,a[i].age,a[i].gender,a[i].num);
    }
}*/

//    EXERCISE 16.1
/*struct student
{
    char name[20];
    char surname[20];
    float point;

}a[10];

void read(struct student *ptr,char input[],int i)
{
    sscanf(input,"%[^;];%[^;];",ptr->name,ptr->surname);
}
void write(struct student ptr[])
{
    for (int i = 0; i < 10; i++)
    {
        printf("%s %s %.2f\n",ptr->name,ptr->surname,ptr->point);
        ptr++;
    }
}

int main()
{
    char input[30];

    for (int i = 0; i < 10; i++)
    {
        fflush(stdin);
        printf("%d The student's name,surname and notes: ",i+1);
        fgets(input,30,stdin);
        scanf("%f", &a[i].point);
        read(&a[i],input,i);
    }
    printf("-----LIST-----\n");

    write(a);
    
}*/


//    EXERCISE 16.2
/*struct student
{
    char name[20];
    char surname[20];
    float point;

}a[10];

void read(struct student *ptr,char input[],int i)
{
    sscanf(input,"%[^;];%[^;];",ptr->name,ptr->surname);
}
void write(struct student ptr[])
{
    for (int i = 0; i < 10; i++)
    {
        printf("%s %s %.2f\n",ptr->name,ptr->surname,ptr->point);
        ptr++;
    }
}
void compare(struct student *ptr)
{
    char rname[20];
    char rsurname[20];
    float rpoint;
    for (int i = 0; i < 10; i++)
    {
        for (int j = 0; j < 9; j++)
        {
            for (int k = 1; k < strlen(ptr[j].surname); k++)
            {
            printf("result :%d k:%d j:%d\n", strncmp(ptr[j].surname,ptr[j+1].surname,k*sizeof(char)),k,j);
             
            if(strncmp(ptr[j].surname,ptr[j+1].surname,k*sizeof(char)) >= 1)
            {
                strcpy(rname,ptr[j+1].name);
                strcpy(ptr[j+1].name,ptr[j].name);
                strcpy(ptr[j].name,rname);
                strcpy(rsurname,ptr[j+1].surname);
                strcpy(ptr[j+1].surname,ptr[j].surname);
                strcpy(ptr[j].surname,rsurname);
                rpoint = ptr[j+1].point;
                ptr[j+1].point = ptr[j].point;
                ptr[j].point = rpoint;
                break;
            }
            else if (strncmp(ptr[j].surname,ptr[j+1].surname,k*sizeof(char)) == 0)
            {
                continue;
            }
            
            }
        }  
    }
}
int main()
{
    char input[30];

    for (int i = 0; i < 10; i++)
    {
        fflush(stdin);
        printf("%d The student's name,surname and notes: ",i+1);
        fgets(input,30,stdin);
        scanf("%f", &a[i].point);
        read(&a[i],input,i);
    }
    printf("-----LIST-----\n");
    compare(&a);
    write(a);
}*/

//    EXERCISE 16.3
/*struct zaman{
    int hour;
    int min;
    int sc;

};
void produceTime(struct zaman *tptr)
{
    srand(time(NULL));
    tptr->hour= rand() %24;
    tptr->min= rand() %60;
    tptr->sc= rand() %60;
}
void addtime(struct zaman *ptr,int x)
{
    ptr->sc= ptr->sc + x;
    if (ptr->sc >= 60)
    {
        ptr->min= ptr->min+ptr->sc/60;
        ptr->sc= ptr->sc%60;
    }
    if (ptr->min >= 60)
    {
        ptr->hour=ptr->hour+ptr->min/60;
        ptr->min= ptr->min%60;
    }
    if (ptr->hour >= 24)
    {
        ptr->hour= -1;
        ptr->min= -1;
        ptr->sc= -1;
    }

    
}
int main()
{
    struct zaman t1;
    int tsc;
    produceTime(&t1);
    printf("The time generated by the program: %d:%d:%d",t1.hour,t1.min,t1.sc);
    printf("\nEnter how many seconds you want to add:");
    scanf("%d",&tsc);
    addtime(&t1,tsc);
    printf("\nYour new time: %d:%d:%d",t1.hour,t1.min,t1.sc);
}*/

//    EXERCISE 16.4
/*struct zaman{
    int hour;
    int min;
    int sc;

};
void addtime(struct zaman *ptr,struct zaman tadd)
{
    ptr->sc= ptr->sc + tadd.sc;
    if (ptr->sc >= 60)
    {
        ptr->min= ptr->min+ptr->sc/60;
        ptr->sc= ptr->sc%60;
    }
    ptr->min= ptr->min + tadd.min;
    if (ptr->min >= 60)
    {
        ptr->hour=ptr->hour+ptr->min/60;
        ptr->min= ptr->min%60;
    }
    ptr->hour= ptr->hour + tadd.hour;
    if (ptr->hour >= 24)
    {
        ptr->hour= 0;
    }
}
int main()
{
    struct zaman t1 ={23,30,20};
    struct zaman t2 ={1,0,40};

    addtime(&t1,t2);
    printf("\nYour new time: %d:%d:%d",t1.hour,t1.min,t1.sc);
}*/
