#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <time.h>
#include <ctype.h>
#include <string.h>

/*struct student
{
    char name[10];
    int age;
    char gender;
    int num;

}a[20];

int main()
{
    int studentsN;
    printf("How many students are you going to enter (max:20): ");
    scanf("%d",&studentsN);
    for (int i = 0; i < studentsN; i++)
    {
        printf("Enter the name: ");
        fflush(stdin);
        scanf("%s", &a[i].name);
        printf("How old is the student: ");
        scanf("%d", &a[i].age);
        printf("The student's gender: ");
        fflush(stdin);
        scanf("%c", &a[i].gender);
        printf("The student's number: ");
        scanf("%d", &a[i].num);
    }

    for (int i = 0; i < studentsN; i++)
    {
        printf("%d. student's card:\nName:%s\nAge:%d\nGender:%c\nNum:%d",i+1,a[i].name,a[i].age,a[i].gender,a[i].num);
    }
}*/

//    EXERCISE 16.1
/*struct student
{
    char name[20];
    char surname[20];
    float point;

}a[10];

void read(struct student *ptr,char input[],int i)
{
    sscanf(input,"%[^;];%[^;];",ptr->name,ptr->surname);
}
void write(struct student ptr[])
{
    for (int i = 0; i < 10; i++)
    {
        printf("%s %s %.2f\n",ptr->name,ptr->surname,ptr->point);
        ptr++;
    }
}

int main()
{
    char input[30];

    for (int i = 0; i < 10; i++)
    {
        fflush(stdin);
        printf("%d The student's name,surname and notes: ",i+1);
        fgets(input,30,stdin);
        scanf("%f", &a[i].point);
        read(&a[i],input,i);
    }
    printf("-----LIST-----\n");

    write(a);
    
}*/


//    EXERCISE 16.2
/*struct student
{
    char name[20];
    char surname[20];
    float point;

}a[10];

void read(struct student *ptr,char input[],int i)
{
    sscanf(input,"%[^;];%[^;];",ptr->name,ptr->surname);
}
void write(struct student ptr[])
{
    for (int i = 0; i < 10; i++)
    {
        printf("%s %s %.2f\n",ptr->name,ptr->surname,ptr->point);
        ptr++;
    }
}
void compare(struct student *ptr)
{
    char rname[20];
    char rsurname[20];
    float rpoint;
    for (int i = 0; i < 10; i++)
    {
        for (int j = 0; j < 9; j++)
        {
            for (int k = 1; k < strlen(ptr[j].surname); k++)
            {
            printf("result :%d k:%d j:%d\n", strncmp(ptr[j].surname,ptr[j+1].surname,k*sizeof(char)),k,j);
             
            if(strncmp(ptr[j].surname,ptr[j+1].surname,k*sizeof(char)) >= 1)
            {
                strcpy(rname,ptr[j+1].name);
                strcpy(ptr[j+1].name,ptr[j].name);
                strcpy(ptr[j].name,rname);
                strcpy(rsurname,ptr[j+1].surname);
                strcpy(ptr[j+1].surname,ptr[j].surname);
                strcpy(ptr[j].surname,rsurname);
                rpoint = ptr[j+1].point;
                ptr[j+1].point = ptr[j].point;
                ptr[j].point = rpoint;
                break;
            }
            else if (strncmp(ptr[j].surname,ptr[j+1].surname,k*sizeof(char)) == 0)
            {
                continue;
            }
            
            }
        }  
    }
}
int main()
{
    char input[30];

    for (int i = 0; i < 10; i++)
    {
        fflush(stdin);
        printf("%d The student's name,surname and notes: ",i+1);
        fgets(input,30,stdin);
        scanf("%f", &a[i].point);
        read(&a[i],input,i);
    }
    printf("-----LIST-----\n");
    compare(&a);
    write(a);
}*/

//    EXERCISE 16.3
/*struct zaman{
    int hour;
    int min;
    int sc;

};
void produceTime(struct zaman *tptr)
{
    srand(time(NULL));
    tptr->hour= rand() %24;
    tptr->min= rand() %60;
    tptr->sc= rand() %60;
}
void addtime(struct zaman *ptr,int x)
{
    ptr->sc= ptr->sc + x;
    if (ptr->sc >= 60)
    {
        ptr->min= ptr->min+ptr->sc/60;
        ptr->sc= ptr->sc%60;
    }
    if (ptr->min >= 60)
    {
        ptr->hour=ptr->hour+ptr->min/60;
        ptr->min= ptr->min%60;
    }
    if (ptr->hour >= 24)
    {
        ptr->hour= -1;
        ptr->min= -1;
        ptr->sc= -1;
    }

    
}
int main()
{
    struct zaman t1;
    int tsc;
    produceTime(&t1);
    printf("The time generated by the program: %d:%d:%d",t1.hour,t1.min,t1.sc);
    printf("\nEnter how many seconds you want to add:");
    scanf("%d",&tsc);
    addtime(&t1,tsc);
    printf("\nYour new time: %d:%d:%d",t1.hour,t1.min,t1.sc);
}*/

//    EXERCISE 16.4
/*struct zaman{
    int hour;
    int min;
    int sc;

};
void addtime(struct zaman *ptr,struct zaman tadd)
{
    ptr->sc= ptr->sc + tadd.sc;
    if (ptr->sc >= 60)
    {
        ptr->min= ptr->min+ptr->sc/60;
        ptr->sc= ptr->sc%60;
    }
    ptr->min= ptr->min + tadd.min;
    if (ptr->min >= 60)
    {
        ptr->hour=ptr->hour+ptr->min/60;
        ptr->min= ptr->min%60;
    }
    ptr->hour= ptr->hour + tadd.hour;
    if (ptr->hour >= 24)
    {
        ptr->hour= 0;
    }
}
int main()
{
    struct zaman t1 ={23,30,20};
    struct zaman t2 ={1,0,40};

    addtime(&t1,t2);
    printf("\nYour new time: %d:%d:%d",t1.hour,t1.min,t1.sc);
}*/


//    EXERCISE 16.5
/*struct zaman{
    int hour;
    int min;
    int sc;

};
void compare(struct zaman *ptr1,struct zaman *ptr2)
{
    int rhour;
    int rmin;
    int rsc;
    if (ptr2->hour < ptr1->hour)
    {
        rhour=ptr1->hour;
        ptr1->hour = ptr2->hour;
        ptr2->hour =rhour;
        rmin=ptr1->min;
        ptr1->min = ptr2->min;
        ptr2->min =rmin;
        rsc=ptr1->sc;
        ptr1->sc = ptr2->sc;
        ptr2->sc =rsc;
    }
    else if (ptr2->min < ptr1->min && ptr2->hour == ptr1->hour)
    {
        rhour=ptr1->hour;
        ptr1->hour = ptr2->hour;
        ptr2->hour =rhour;
        rmin=ptr1->min;
        ptr1->min = ptr2->min;
        ptr2->min =rmin;
        rsc=ptr1->sc;
        ptr1->sc = ptr2->sc;
        ptr2->sc =rsc;
    }
    else if (ptr2->sc < ptr1->sc && ptr2->min == ptr1->min && ptr2->hour == ptr1->hour)
    {
        rhour=ptr1->hour;
        ptr1->hour = ptr2->hour;
        ptr2->hour =rhour;
        rmin=ptr1->min;
        ptr1->min = ptr2->min;
        ptr2->min =rmin;
        rsc=ptr1->sc;
        ptr1->sc = ptr2->sc;
        ptr2->sc =rsc;
    }
}
int main()
{
    typedef struct zaman Time;
    Time t1 ={2,23,0};
    Time t2 ={2,0,40};

    compare(&t1,&t2);
    printf("\n1.time: %d:%d:%d",t1.hour,t1.min,t1.sc);
    printf("\n2.time: %d:%d:%d",t2.hour,t2.min,t2.sc);
}*/

//    EXERCISE 16.6
/*struct zaman{
    int hour;
    int min;
    int sc;

};
void soustract(struct zaman t1,struct zaman t2,struct zaman *ptrT)
{
    ptrT->hour = abs(t1.hour-t2.hour);
    ptrT->min = abs(t1.min-t2.min);
    ptrT->sc = abs(t1.sc-t2.sc);

}
int main()
{
    typedef struct zaman Time;
    Time t1;
    Time t2;
    Time tS;

    printf("Enter the 1.time: ");
    scanf("%d %d %d",&t1.hour,&t1.min,&t1.sc);
    printf("Enter the 2.time: ");
    scanf("%d %d %d",&t2.hour,&t2.min,&t2.sc);
    soustract(t1,t2,&tS);
    printf("The difference between the times is %d hour(s) %d minute(s) and %d second(s).",tS.hour,tS.min,tS.sc);
}*/

//    EXERCISE 16.7
/*struct date{
    int day;
    int month;
    int year;

};
int compare(struct date t1,struct date t2,struct date *ptrT)
{
    ptrT->day = t1.day;
    ptrT->month = t1.month;
    ptrT->year = t1.year;

    if (t2.year > t1.year)
    {
        ptrT->day = t1.day;
        ptrT->month = t1.month;
        ptrT->year = t1.year;
    } else if (t2.year == t1.year && t2.month > t1.month)
    {
        ptrT->day = t1.day;
        ptrT->month = t1.month;
        ptrT->year = t1.year;
    }else if (t2.year == t1.year && t2.month == t1.month && t2.day > t1.day)
    {
        ptrT->day = t1.day;
        ptrT->month = t1.month;
        ptrT->year = t1.year;
    }
    else if (t2.year == t1.year && t2.month == t1.month && t2.day == t1.day)
    {
        return 1;
    }
    return 0;
}
int main()
{
    typedef struct date Date;
    Date t1;
    Date t2;
    Date tS;

    printf("Enter the 1.date: ");
    scanf("%d %d %d",&t1.day,&t1.month,&t1.year);
    printf("Enter the 2.date: ");
    scanf("%d %d %d",&t2.day,&t2.month,&t2.year);
    compare(t1,t2,&tS);
    if (compare(t1,t2,&tS))
    {
        printf("The dates are the same: %d/%d/%d.",tS.day,tS.month,tS.year);
    }else
        printf("The nearest date is %d/%d/%d.",tS.day,tS.month,tS.year);
}*/

//    EXERCISE 16.8
/*struct student{
    int table;
    char name[20];
    char surname[20];
    float note;
    char sex;
};
void switched(struct student *ptr1,struct student *ptr2)
{
    int tabler= ptr1->table;
    float noter= ptr1->note;
    char sexr= ptr1->sex;
    char namer[20];
    char surnamer[20];
    strcpy(namer,ptr1->name);
    strcpy(surnamer,ptr1->surname);

    ptr1->table= ptr2->table;
    ptr1->note= ptr2->note;
    ptr1->sex= ptr2->sex;
    strcpy(ptr1->name,ptr2->name);
    strcpy(ptr1->surname,ptr2->surname);

    ptr2->table= tabler;
    ptr2->note= noter;
    ptr2->sex= sexr;
    strcpy(ptr2->name,namer);
    strcpy(ptr2->surname,surnamer);
}
int main()
{
    typedef struct student Student;
    Student a1= {2,"Talha","Korkmaz",3.15,'E'};
    Student a2= {5,"Alperen","Palak",1.9,'K'};

    switched(&a1,&a2);
    printf("a1: %d,%s,%s,%.2f,'%c'",a1.table,a1.name,a1.surname,a1.note,a1.sex);
    printf("\na2: %d,%s,%s,%.2f,'%c'",a2.table,a2.name,a2.surname,a2.note,a2.sex);
}*/

//    EXERCISE 16.9
/*struct customer{
    int table;
    char namefull[50];
    char number[15];
    float debt;
    char sex;
};
void switched(struct customer *ptr1,struct customer *ptr2)
{
    int tabler= ptr1->table;
    float debtr= ptr1->debt;
    char sexr= ptr1->sex;
    char namer[50];
    char numberr[15];
    strcpy(namer,ptr1->namefull);
    strcpy(numberr,ptr1->number);

    ptr1->table= ptr2->table;
    ptr1->debt= ptr2->debt;
    ptr1->sex= ptr2->sex;
    strcpy(ptr1->namefull,ptr2->namefull);
    strcpy(ptr1->number,ptr2->number);

    ptr2->table= tabler;
    ptr2->debt= debtr;
    ptr2->sex= sexr;
    strcpy(ptr2->namefull,namer);
    strcpy(ptr2->number,numberr);
}
int main()
{
    typedef struct customer C;
    C a1= {4,"Zeynep Akdag","4241",1000.45,'K'};
    C a2= {2,"Talha Korkmaz","2983",10.05,'E'};
    C a3= {5,"Alperen Palak","2841",500.05,'K'};

    for (int i = 0; i < 2; i++)
    {
        if (a1.debt > a2.debt)
        {
            switched(&a1,&a2);
        }
        if (a2.debt > a3.debt)
        {
            switched(&a2,&a3);
        }
    }
    
    printf("a1: %d,%s,%s,%.2f,'%c'",a1.table,a1.namefull,a1.number,a1.debt,a1.sex);
    printf("\na2: %d,%s,%s,%.2f,'%c'",a2.table,a2.namefull,a2.number,a2.debt,a2.sex);
    printf("\na3: %d,%s,%s,%.2f,'%c'",a3.table,a3.namefull,a3.number,a3.debt,a3.sex);
}*/

//    EXERCISE 16.10
/*struct circle{
    int x;
    int y;
    float r;
};
void Findtheeater(struct circle a,struct circle b,struct circle *cptr)
{
    if (sqrt(pow(a.x-b.x,2)+pow(a.y-b.y,2))+a.r <= b.r)
    {
        cptr->x= b.x;
        cptr->y= b.y;
        cptr->r= b.r;
    }
    else if (sqrt(pow(a.x-b.x,2)+pow(a.y-b.y,2))+b.r <= a.r)
    {
        cptr->x= a.x;
        cptr->y= a.y;
        cptr->r= a.r;
    }
    
    
}
int main()
{
    typedef struct circle Circle;
    Circle a= {10,8,4.0}, b= {15,10,13.0},c;

    Findtheeater(a,b,&c);
    printf("c coordinates : (%d,%d) and ray: %.2f",c.x,c.y,c.r);
}*/

//    EXERCISE 16.11
/*struct circle{
    float x;
    float y;
    float r;
};
void moveCircle(struct circle *ptr,char tangent)
{
    switch (tangent)
    {
    case 'x':
    case 'X':
        if (ptr->y < 0)
        {
            ptr->y=ptr->r*-1;
        }else
        ptr->y=ptr->r;
        break;
        ptr->y=ptr->r;
        break;
    case 'y':
    case 'Y':
        if (ptr->x < 0)
        {
            ptr->x=ptr->r*-1;
        }else
        ptr->x=ptr->r;
        break;
    } 
}
int main()
{
    typedef struct circle Circle;
    Circle a;
    char tangent;
    printf("Which axis do you want it to be tangent:");
    fflush(stdin);
    scanf("%c",&tangent);
    printf("Enter your circle's coordinates and ray: ");
    scanf("%f %f %f",&a.x,&a.y,&a.r);

    moveCircle(&a,tangent);
    printf("The circle's new centerX: %.1f centerY: %.1f and ray: %.1f",a.x,a.y,a.r);
}*/

//    EXERCISE 16.12
/*struct circle{
    int x;
    int y;
    int r;
};
int isSoddy(struct circle a,struct circle b,struct circle c)
{
    int r1 = sqrt(pow(a.x-b.x,2)+pow(a.y-b.y,2));
    int r2 = sqrt(pow(a.x-c.x,2)+pow(a.y-c.y,2));
    int r3 = sqrt(pow(c.x-b.x,2)+pow(c.y-b.y,2));
    if (r1 == a.r+b.r && r2 == a.r+c.r && r3 == c.r+b.r)
    {
        return 1;
    }
    else
        return 0;
    
}
int main()
{
    typedef struct circle Circle;
    Circle a,b,c;

    printf("Enter your 1.circle's coordinates and ray: ");
    scanf("%d %d %d",&a.x,&a.y,&a.r);
    printf("Enter your 2.circle's coordinates and ray: ");
    scanf("%d %d %d",&b.x,&b.y,&b.r);
    printf("Enter your 3.circle's coordinates and ray: ");
    scanf("%d %d %d",&c.x,&c.y,&c.r);

    if (isSoddy(a,b,c))
    {
        printf("These circles are Soddy.");
    }
    else
         printf("These circles aren't Soddy.");
}*/

//    EXERCISE 16.13
/*struct student{
    char no[10];
    float point;
    int credit;
    int year;
};
void findSuccess(struct student a,struct student b,struct student *ptrS)
{
    if (a.point > b.point || a.point == b.point && a.credit < b.credit || a.point == b.point && a.credit == b.credit && a.year > b.year)
    {
        ptrS->point= a.point;
        ptrS->credit= a.credit;
        ptrS->year= a.year;
        strcpy(ptrS->no,a.no);
    }else{
        ptrS->point= b.point;
        ptrS->credit= b.credit;
        ptrS->year= b.year;
        strcpy(ptrS->no,b.no);
    }
}
int main()
{
    typedef struct student Stu;
    Stu a,b,s;

    printf("Enter your 1.student's num, overall average, total credit and his starting year: ");
    fflush(stdin);
    fgets(a.no,10,stdin);
    scanf("%f %d %d",&a.point,&a.credit,&a.year);
    printf("Enter your 2.student's num, overall average, total credit and his starting year: ");
    fflush(stdin);
    fgets(b.no,10,stdin);
    scanf("%f %d %d",&b.point,&b.credit,&b.year);

    findSuccess(a,b,&s);
    printf("The successful student is the number %s student.(overall average: %.2f, credit: %d, entering year: %d)",s.no,s.point,s.credit,s.year);
}*/
